dist: bionic
language: node_js
node_js:
  - lts/*
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  verbose: true
  on:
    branch: master
